/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/user': {
    get: operations['getUser'];
    post: operations['addUser'];
  };
  '/users': {
    get: operations['getUsers'];
  };
  '/quest': {
    get: operations['getQuest'];
    post: operations['addQuest'];
  };
  '/quests': {
    get: operations['getQuests'];
  };
  '/guild/quest': {
    get: operations['getGuildQuest'];
    post: operations['addGuildQuest'];
  };
  '/guild/quests': {
    get: operations['getGuildQuests'];
  };
  '/guild': {
    get: operations['getGuild'];
    post: operations['addGuild'];
  };
  '/guilds': {
    get: operations['getGuilds'];
  };
  '/notices': {
    get: operations['getNotices'];
  };
}

export interface components {
  schemas: {
    User: {
      public_key: string;
      name: string;
      /** @description base64 encoding */
      icon: string;
    };
    UserTable: components['schemas']['User'] & {
      /** @description new Date().getTime() */
      created: number;
    };
    Quest: {
      quest_id: string;
      nominate_guild_id: string;
      transaction_hash: string;
      title: string;
      description: string;
      reward: number;
      requester_public_key: string;
      worker_public_key: string;
      /** @enum {string} */
      status: 'WANTED' | 'WORKING' | 'COMPLETED';
    };
    QuestTable: components['schemas']['Quest'] & {
      quest_id: string;
      /** @description new Date().getTime() */
      created: number;
    };
    Notice: {
      notice_id: string;
      title: string;
      body: string;
      public_key: string;
      /** @description new Date().getTime() */
      created: number;
    };
    Guild: {
      public_key?: string;
      name: string;
      /** @description base64 encoding */
      icon: string;
    } & {
      owner_public_key: unknown;
    };
    GuildTable: components['schemas']['Guild'] &
      ({
        guild_id: string;
        /** @description new Date().getTime() */
        created?: number;
      } & {
        creatd: unknown;
      });
  };
}

export interface operations {
  getUser: {
    parameters: {
      query: {
        public_key: string;
      };
    };
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['UserTable'];
        };
      };
      /** Successful & but no content */
      204: {
        content: {
          'application/json': {
            /** @enum {string} */
            message?: 'unregistered';
          };
        };
      };
    };
  };
  addUser: {
    responses: {
      /** Successful operation */
      200: {
        content: {
          'application/json': components['schemas']['UserTable'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['User'];
      };
    };
  };
  getUsers: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['UserTable'][];
        };
      };
    };
  };
  getQuest: {
    parameters: {
      query: {
        public_key: string;
      };
    };
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'];
        };
      };
    };
  };
  addQuest: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'];
        };
      };
    };
    /** to blank transaction_hash, transaction_hash */
    requestBody: {
      content: {
        'application/json': components['schemas']['Quest'];
      };
    };
  };
  getQuests: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'][];
        };
      };
    };
  };
  getGuildQuest: {
    parameters: {
      query: {
        public_key: string;
      };
    };
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'];
        };
      };
    };
  };
  addGuildQuest: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'];
        };
      };
    };
    /** to blank transaction_hash, transaction_hash */
    requestBody: {
      content: {
        'application/json': components['schemas']['Quest'];
      };
    };
  };
  getGuildQuests: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['QuestTable'][];
        };
      };
    };
  };
  getGuild: {
    parameters: {
      query: {
        guild_id: string;
      };
    };
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['GuildTable'];
        };
      };
    };
  };
  addGuild: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['GuildTable'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Guild'];
      };
    };
  };
  getGuilds: {
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['GuildTable'][];
        };
      };
    };
  };
  getNotices: {
    parameters: {
      query: {
        public_key: string;
      };
    };
    responses: {
      /** Successful */
      200: {
        content: {
          'application/json': components['schemas']['Notice'][];
        };
      };
    };
  };
}

export interface external {}
